name: amount_to_word
description: A comprehensive Flutter package for converting numbers and amounts to words in multiple languages (Persian, English, Turkish) with full currency support and smart pluralization.
version: 2.0.1
homepage: https://github.com/ialirezairanmanesh/amount_to_word
repository: https://github.com/ialirezairanmanesh/amount_to_word
issue_tracker: https://github.com/ialirezairanmanesh/amount_to_word/issues
documentation: https://pub.dev/documentation/amount_to_word/latest/

topics:
  - localization
  - currency
  - numbers
  - multilingual
  - persian


environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Package does not need Flutter localization dependencies
# as it implements its own lightweight localization system

flutter:
  # This package does not contain any assets or fonts
  # It's a pure Dart logic package with Flutter integration